language: ruby
rvm:
- 2.0.0
- 2.1.5
- 2.2.1
sbefore_script:
- wget http://ftp.gnu.org/gnu/bison/bison-3.0.2.tar.gz
- tar xf bison-3.0.2.tar.gz
- cd bison-3.0.2
- ./configure
- make
- sudo make install
- cd ..
- sudo apt-get install flex libonig2 libonig-dev
- git clone https://github.com/stedolan/jq.git
- cd jq
- autoreconf -i
- ./configure --enable-shared
- BUNDLE_GEMFILE="$PWD/docs/Gemfile" bundle install
- BUNDLE_GEMFILE="$PWD/docs/Gemfile" bundle exec make
- sudo make install
- sudo ldconfig
- cd ..
script:
- bundle install
- bundle exec rake
